"""add payment and session fields

Revision ID: a96d0b74b1af
Revises: 
Create Date: 2026-06-17 12:19:45.878681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96d0b74b1af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_used_free', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('has_paid', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('session_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_session_token'), ['session_token'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_session_token'))
        batch_op.drop_column('session_token')
        batch_op.drop_column('has_paid')
        batch_op.drop_column('has_used_free')

    # ### end Alembic commands ###
